[font]
size = 12.0


[font.normal]
family = "3270 Nerd Font Mono"
style = "Regular"

[font.bold]
family = "3270 Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "3270 Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "3270 Nerd Font Mono"
style = "Italic"
