[colors]

draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0xffcc00"
blue = "0xffcc00"
cyan = "0xffcc00"
green = "0xffcc00"
magenta = "0xffcc00"
red = "0xffcc00"
white = "0xffcc00"
yellow = "0xffcc00"

[colors.normal]
black = "0x282828"
blue = "0xffcc00"
cyan = "0xffcc00"
green = "0xffcc00"
magenta = "0xffcc00"
red = "0xffcc00"
white = "0xffcc00"
yellow = "0xffcc00"

[colors.primary]
background = "0x282828"
foreground = "0xffcc00"
