[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x505050"
blue = "0x6fc2ef"
cyan = "0x12cfc0"
green = "0xacc267"
magenta = "0xe1a3ee"
red = "0xfb9fb1"
white = "0xf5f5f5"
yellow = "0xddb26f"

[colors.normal]
black = "0x151515"
blue = "0x6fc2ef"
cyan = "0x12cfc0"
green = "0xacc267"
magenta = "0xe1a3ee"
red = "0xfb9fb1"
white = "0xd0d0d0"
yellow = "0xddb26f"

[colors.primary]
background = "0x151515"
foreground = "0xd0d0d0"
